name: Foodie CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test --stacktrace
  
  ios_build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build IOS
      uses: sparkfabrik/ios-build-action@v1.1.0
      with:
        project-path: iosApp/iosApp.xcodeproj
        workspace-path: iosApp/iosApp.xcworkspace

