name: Foodie CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Test with Gradle
      run: ./gradlew test --stacktrace
  
  ios_build:
    
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.3.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild clean test -scheme iosApp -workspace iosApp/iosApp.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=14.3' | xcpretty && exit ${PIPESTATUS[0]}

